#### Linear Algebra in NumPy

In [19]:
import numpy as np

#### Basics: Vectors and Matrices

In [20]:
# Creating Vectors

# vectors are essentially one-dimensional arrays in NumPy
v = np.array([1,2,3])
print("vector: ", v)

# Creating Matrices
# matrices are two-dimensional arrays
m = np.array([[1,2,3],[4,5,6]])
print("matrix: \n", m)

vector:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]


### Basic Linear Algebra Operations

In [21]:
# Vector Addition and Subtraction
# operations are element-wise
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("addition: ", v1 + v2)
print("subtraction :", v1 - v2)

addition:  [5 7 9]
subtraction : [-3 -3 -3]


In [22]:
# Scalar Multiplication
# multiply a scalar with a vector or matrix
scalar = 3
print("(vector): ", scalar*v)
print("(matrix):\n",scalar*m)

(vector):  [3 6 9]
(matrix):
 [[ 3  6  9]
 [12 15 18]]


In [23]:
# Matrix Addition and Subtraction
# must of same dimensions
m1 = np.array([[1,2],[4,5]])
m2 = np.array([[4,6],[8,9]])
print("addition:\n", m1+m2)
print("subtraction:\n", m1-m2)

addition:
 [[ 5  8]
 [12 14]]
subtraction:
 [[-3 -4]
 [-4 -4]]


In [24]:
# Dot Product of Vectors
# the dot product of two vectors is a scalar
dot_product = np.dot(v1,v2)
print(dot_product)

32


In [26]:
# Matrix Multiplication
# use np.dot or the @ operator to perform matrix multiplication
result = np.dot(m1,m2)
print("(dot):\n",result)
result = m1@m2
print("(@):\n",result)

(dot):
 [[20 24]
 [56 69]]
(@):
 [[20 24]
 [56 69]]


In [27]:
# Transpose of a Matrix
# swap rows and columns
print("transpose of m1:\n", m1.T)

transpose of m1:
 [[1 4]
 [2 5]]


In [28]:
# Element Wise Multiplication
# use *
elementwise = m1*m2
print(elementwise)

[[ 4 12]
 [32 45]]


## `np.linalg` functions

##### Solving Systems of Linear Equations (`np.linalg.solve`)
A system of linear equations can be written in matrix form as $ Ax = b $, where:
- $ A $ is a matrix of coefficients,
- $ x $ is a column vector of variables,
- $ b $ is a column vector of constants <br>
The solution, $ x $ represents the values of variables that satisfy all equations simultaneously. <br>
If $ A $ is invertible, we can find $ x $ by calculating $ x = A^{-1} b $
<br>
- np.linalg.solve(A,b) is specially designed to solve for $ x $ efficiently without explicitly computing $ A^{-1} $ which is computationally expensive


In [29]:
A = np.array([[2,1],[1,3]])
b = np.array([8,13])
x = np.linalg.solve(A,b)
print("x: ",x)

x:  [2.2 3.6]


##### Inverse of a Matrix (`np.linalg.inv`)
- The inverse of a matrix $A$, denoted $A^{-1}$, is defined such that $ A.A^{-1} = I $, where $I$ is the identity matrix
- Inverting a matrix is only possible if the matrix is square and non-singular (determinant ≠ 0)

In [30]:
inverse_A = np.linalg.inv(A)
print("Inverse of A: \n", inverse_A)

Inverse of A: 
 [[ 0.6 -0.2]
 [-0.2  0.4]]


##### Determinant of a Matrix (`np.linalg.det`)
- A zero determinant indicates that the matrix is singular (non-invertible)
- The absolute value of the determinant can be interpreted as the "volume scaling factor" of the linear transformation represented by the matrix

- useful for determining invertibility and understanding transformations
- If det(A) ≠ 0, the system has a unique solution.
- If det(A) = 0, the system either has no solution or an infinite number of solutions.

In [31]:
det_A = np.linalg.det(A)
print("determinant of A:", det_A)

determinant of A: 5.000000000000001


##### Eigenvalues and Eigenvectors (`np.linalg.eig`)
For a square matrix $A$, an eigenvector $V$ and its corresponding eigenvalue $\lambda $ satisfy the equation: $Av = \lambda v$
- Eigenvalues tell us about the "stretching" factor along the direction of their corresponding eigenvectors
- Eigenvectors give directions that remain unchanged by the transformation AA, except for scaling

- np.linalg.eig(A) returns eigenvalues and eigenvectors of A

In [32]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n",eigenvectors)

Eigenvalues: [1.38196601 3.61803399]
Eigenvectors:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


##### Matrix Norms (`np.linalg.norm`)
The norm of a vector or matrix is a measure of its "size" or "length"
- **L2 norm** (Euclidean) measures the straight-line distance from the origin
- **L1 norm** (Manhattan) measures distance by summing absolute values of each component
- ther norms, such as Frobenius norm, are used specifically for matrices

- np.linalg.norm(x, ord=None) computes various norms depending on the value of ord
- Common norms: L2 norm (default), L1 norm (ord=1), infinity norm (ord=np.inf)

In [33]:
x = np.array([3,4])
norm_x = np.linalg.norm(x) # default L2 norm
print("Norm: ",norm_x)

Norm:  5.0


##### Singular Value Decomposition (SVD) (`np.linalg.svd`)
SVD decomposes a matrix AAA into three matrices: $ A=U \Sigma V^∗ $

-   UUU: Left singular vectors, representing orthogonal directions.
-   Σ\SigmaΣ: Diagonal matrix of singular values, showing the amount of stretching in each direction.
-   V∗V^*V∗: Right singular vectors, representing orthogonal directions in the output space.

-   `np.linalg.svd(A)` returns the matrices U, $\Sigma$, and V^*.
-   SVD is essential in data compression, dimensionality reduction, and image processing.

In [34]:
C = np.array([[1, 2], [3, 4], [5, 6]])

U, Sigma, Vt = np.linalg.svd(C)
print("U:\n", U)
print("Sigma:", Sigma)
print("Vt:\n", Vt)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma: [9.52551809 0.51430058]
Vt:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


##### QR Decomposition (`np.linalg.qr`)
QR decomposition factors a matrix AAA into: $ A=QR $

-   Q: An orthogonal matrix.
-   R: An upper triangular matrix.

-   `np.linalg.qr(A)` returns Q and R.
-   Useful for solving linear systems and least-squares fitting.

In [35]:
C = np.array([[1, 2], [3, 4], [5, 6]])

U, Sigma, Vt = np.linalg.svd(C)
print("U:\n", U)
print("Sigma:", Sigma)
print("Vt:\n", Vt)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma: [9.52551809 0.51430058]
Vt:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


##### Cholesky Decomposition (`np.linalg.cholesky`)
Cholesky decomposition is a specific decomposition for symmetric, positive-definite matrices: $A=LL^T$

-   L: A lower triangular matrix.
-   Faster than other decompositions, making it suitable for numerical methods where positive-definite matrices are guaranteed (e.g., in optimization problems).

-   `np.linalg.cholesky(A)` returns L.
-   Limited to positive-definite matrices; used in optimization and simulation

In [36]:
E = np.array([[4, 2], [2, 3]])

L = np.linalg.cholesky(E)
print("Cholesky factor L:\n", L)

Cholesky factor L:
 [[2.         0.        ]
 [1.         1.41421356]]


##### Trace of a Matrix (`np.trace`)
The trace of a matrix is the sum of its diagonal elements
- Represents an invariant under change of basis
- Often used in matrix transformations and certain types of optimizations
- Useful in many areas, such as physics in machine learning

In [37]:
F = np.array([[1, 2], [3, 4]])

trace_F = np.trace(F)
print("Trace of F:", trace_F)

Trace of F: 5


#####  Condition Number (`np.linalg.cond`)
The conditional number measures how sensitive a matrix is to changes or errors in calculations
- A high condition number means the matrix is "ill-conditioned" and may lead to unstable solutions
- Low values indicate stability and accuracy in calculations
- Useful to evaluate the reliability of solutions when performing matrix inversions or solving equations

In [38]:
G = np.array([[1, 2], [3, 4]])

cond_G = np.linalg.cond(G)
print("Condition number of G:", cond_G)

Condition number of G: 14.933034373659268
