In [13]:
import numpy as np

##### Evaluate the function $ \sqrt{x^2 + y^2} $ across a regular grid of values

In [14]:
# numpy.meshgrid fn takes two one-dim arrays and produce two two-dim matrices corresponding to all pairs of (x, y) in the two arrays

points = np.arange(-3, 3, 0.1)
xs, ys = np.meshgrid(points, points)
print("xs: \n",xs)
print("ys: \n",ys)

xs: 
 [[-3.  -2.9 -2.8 ...  2.7  2.8  2.9]
 [-3.  -2.9 -2.8 ...  2.7  2.8  2.9]
 [-3.  -2.9 -2.8 ...  2.7  2.8  2.9]
 ...
 [-3.  -2.9 -2.8 ...  2.7  2.8  2.9]
 [-3.  -2.9 -2.8 ...  2.7  2.8  2.9]
 [-3.  -2.9 -2.8 ...  2.7  2.8  2.9]]
ys: 
 [[-3.  -3.  -3.  ... -3.  -3.  -3. ]
 [-2.9 -2.9 -2.9 ... -2.9 -2.9 -2.9]
 [-2.8 -2.8 -2.8 ... -2.8 -2.8 -2.8]
 ...
 [ 2.7  2.7  2.7 ...  2.7  2.7  2.7]
 [ 2.8  2.8  2.8 ...  2.8  2.8  2.8]
 [ 2.9  2.9  2.9 ...  2.9  2.9  2.9]]


In [15]:
# now evaluate the function
z = np.sqrt(xs ** 2 + ys ** 2)
print("z: \n",z)

z: 
 [[4.24264069 4.17252921 4.10365691 ... 4.03608721 4.10365691 4.17252921]
 [4.17252921 4.10121933 4.03112887 ... 3.96232255 4.03112887 4.10121933]
 [4.10365691 4.03112887 3.95979797 ... 3.88973007 3.95979797 4.03112887]
 ...
 [4.03608721 3.96232255 3.88973007 ... 3.81837662 3.88973007 3.96232255]
 [4.10365691 4.03112887 3.95979797 ... 3.88973007 3.95979797 4.03112887]
 [4.17252921 4.10121933 4.03112887 ... 3.96232255 4.03112887 4.10121933]]


##### Expressing Conditional Logic as Array Operations

In [25]:
# numpy.where fn is a vectorized version of the ternary expression " x if condition else y " 

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

'''
take value from xarr 
whenever the corresponding value in cond is True,
otherwise take the value from yarr
'''

# by list comprehension
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)

# use numpy.where()
result = np.where(cond, xarr, yarr)
print(result)

# The second and third arguments to numpy.where don’t need to be arrays

[np.float64(1.1), np.float64(2.2), np.float64(1.3), np.float64(1.4), np.float64(2.5)]
[1.1 2.2 1.3 1.4 2.5]


In [29]:
# randomly generate a matrix and replace all +ve value with 2 and all -ve values with -2

arr = np.random.standard_normal((4,4))
print(arr)
print(arr > 0)

np.where(arr > 0, 2, -2)

[[-0.0292509   0.6608574   0.55691719 -1.05628745]
 [-1.00029067 -1.15438013  0.1949741   0.11894854]
 [ 0.65839372 -0.02020603 -1.10444938 -0.00580745]
 [-0.30542461 -1.04966719 -0.19814069  0.63087325]]
[[False  True  True False]
 [False False  True  True]
 [ True False False False]
 [False False False  True]]


array([[-2,  2,  2, -2],
       [-2, -2,  2,  2],
       [ 2, -2, -2, -2],
       [-2, -2, -2,  2]])

In [32]:
# combine scalars and arrays 
np.where(arr > 0, 2, arr) # only set positive values to 2

array([[-0.0292509 ,  2.        ,  2.        , -1.05628745],
       [-1.00029067, -1.15438013,  2.        ,  2.        ],
       [ 2.        , -0.02020603, -1.10444938, -0.00580745],
       [-0.30542461, -1.04966719, -0.19814069,  2.        ]])



| **Approach**         | **Description**                                                                                                      | **Example**                                                                          |
|----------------------|----------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------|
| Boolean Indexing     | Directly apply conditions to filter elements.                                                                       | `array[array > 3] = 0`                                                               |
| `np.where()`         | Vectorized `if-else` replacement.                                                                                   | `np.where(array > 3, 10, array)`                                                     |
| `np.select()`        | Apply different values or functions based on multiple conditions.                                                   | `np.select([cond1, cond2], [choice1, choice2])`                                      |
| Logical Operators    | Combine conditions with `&`, `|`, and `~`.                                                                          | `np.where((array > 2) & (array < 5), -1, array)`                                     |
| Masked Arrays        | Mask elements that meet a condition, ignoring them in further calculations.                                         | `np.ma.masked_where(array > 3, array)`                                               |
| Conditional Functions| Use `np.where()` or boolean indexing to apply different operations conditionally.                                   | `np.where(array < 3, array ** 2, array * 2)`                                         |

These techniques are core to using NumPy for efficient data manipulation, filtering, and computation with conditional logic.

##### Mathematical and Statistical Methods
A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as **methods of the array class**.

In [34]:
arr = np.random.standard_normal((5, 2))
arr

array([[ 0.0198949 , -0.29087381],
       [ 0.27585448,  1.7523927 ],
       [-1.09384082, -0.87024202],
       [ 0.33746399, -0.3093474 ],
       [-1.98369416, -1.40057408]])

In [35]:
arr.mean()

np.float64(-0.3562966216571394)

In [36]:
np.mean(arr)

np.float64(-0.3562966216571394)

In [37]:
print(arr.sum())
print(arr.mean(axis=1)) # across the columns,
print(arr.sum(axis=0))

-3.562966216571394
[-0.13548945  1.01412359 -0.98204142  0.01405829 -1.69213412]
[-2.44432161 -1.1186446 ]


In [38]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr.cumsum())

[ 0  1  3  6 10 15 21 28]


In [39]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


##### Methods for Boolean Arrays

In [42]:
arr = np.random.standard_normal(100)
print((arr > 0).sum()) # number of positive values
print((arr <= 0).sum()) # number of negative values

55
45


In [44]:
# any tests wether one or more values in an array is True, while all checks if every value is True
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())

# These methods also work with non-Boolean arrays, where nonzero elements are treated as True

True
False




| **Method/Function**        | **Description**                                                                                             | **Example**                                                                                          |
|----------------------------|-------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------|
| `np.any()`                 | Checks if at least one element in the array is `True` along the specified axis (or in the entire array).    | `np.any([False, True, False])` ➔ `True`                                                             |
| `np.all()`                 | Checks if all elements in the array are `True` along the specified axis (or in the entire array).           | `np.all([True, True, False])` ➔ `False`                                                             |
| `np.where()`               | Returns the indices of elements that satisfy a condition. Can also be used for conditional replacements.    | `np.where(array > 3)` returns indices of elements > 3                                               |
| `np.nonzero()`             | Returns the indices of `True` elements in the boolean array.                                                | `np.nonzero([False, True, False])` ➔ `(array([1]),)`                                               |
| `np.count_nonzero()`       | Counts the number of `True` elements in the array.                                                          | `np.count_nonzero([False, True, True])` ➔ `2`                                                       |
| `np.logical_and()`         | Element-wise logical `AND` operation between two arrays or conditions.                                      | `np.logical_and([True, False], [True, True])` ➔ `[True, False]`                                     |
| `np.logical_or()`          | Element-wise logical `OR` operation between two arrays or conditions.                                       | `np.logical_or([True, False], [False, False])` ➔ `[True, False]`                                    |
| `np.logical_not()`         | Element-wise logical negation (`NOT`) of the array.                                                         | `np.logical_not([True, False])` ➔ `[False, True]`                                                   |
| `np.logical_xor()`         | Element-wise logical `XOR` (exclusive or) operation between two arrays.                                     | `np.logical_xor([True, False], [False, True])` ➔ `[True, True]`                                     |
| `.any()` (method)          | Checks if at least one element in the array is `True`. Equivalent to `np.any()` but used directly on arrays.| `array.any()`                                                                                        |
| `.all()` (method)          | Checks if all elements in the array are `True`. Equivalent to `np.all()` but used directly on arrays.       | `array.all()`                                                                                        |



##### Sorting

In [46]:
arr = np.random.standard_normal(6)
print(arr)

print(np.sort(arr))

[ 2.61948775  1.29309475  0.94032252  2.20583263 -0.6562154  -0.3469658 ]
[-0.6562154  -0.3469658   0.94032252  1.29309475  2.20583263  2.61948775]


In [48]:
arr = np.random.standard_normal((4,3))
print(arr)

[[ 0.68238778  0.18389642 -1.62393919]
 [-0.21170023 -0.48231745  1.4875443 ]
 [-0.67826417 -1.62475555  0.64322771]
 [-0.7635047   1.67573199 -1.10563468]]


In [51]:
''' 
arr.sort(axis=0) sorts the values within each column, 
while arr.sort(axis=1) sorts across each row
'''
print(np.sort(arr, axis=0))
print(np.sort(arr, axis=1))

# top-level method numpy.sort returns a sorted copy of an array instead of modifying the array in place

[[-0.7635047  -1.62475555 -1.62393919]
 [-0.67826417 -0.48231745 -1.10563468]
 [-0.21170023  0.18389642  0.64322771]
 [ 0.68238778  1.67573199  1.4875443 ]]
[[-1.62475555 -1.62393919 -0.7635047 ]
 [-1.10563468 -0.67826417 -0.48231745]
 [-0.21170023  0.18389642  0.64322771]
 [ 0.68238778  1.4875443   1.67573199]]




| **Function**       | **Description**                                                                                                   | **Example**                                                   |
|--------------------|-------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------|
| `np.sort()`        | Returns a sorted copy of an array along a specified axis.                                                        | `np.sort([3, 1, 2])` ➔ `[1, 2, 3]`                           |
| `np.argsort()`     | Returns the indices that would sort an array.                                                                    | `np.argsort([3, 1, 2])` ➔ `[1, 2, 0]`                        |
| `np.lexsort()`     | Performs an indirect sort using multiple keys. Useful for sorting structured arrays or multiple columns.         | `np.lexsort((ages, names))`                                   |
| `np.msort()`       | Sorts an array along its first axis (similar to `np.sort(a, axis=0)`).                                          | `np.msort([[3, 1], [2, 4]])` ➔ `[[2, 1], [3, 4]]`            |
| `np.partition()`   | Partially sorts an array up to the specified index; elements are rearranged so that the `k`-th element is in its sorted position, and all elements before it are smaller. | `np.partition([3, 1, 2, 4], 2)` ➔ `[1, 2, 3, 4]`             |
| `np.argpartition()`| Returns the indices that would partition an array as in `np.partition()`.                                       | `np.argpartition([3, 1, 2, 4], 2)` ➔ `[1, 2, 0, 3]`          |



##### Unique and Other Set Logic
NumPy has some basic set operations for one-dimensional ndarrays. A commonly used one is numpy.unique, which returns the sorted unique values in an array:

In [60]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)

ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

# numpy.isin, tests membership of the values in one array in another, returning a Boolean array
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.isin(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])



| **Method**            | **Description**                                                                                                                                                             | **Example**                                                                            |
|-----------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|
| `np.unique()`         | Returns the sorted unique elements of an array.                                                                                                                             | `np.unique([1, 2, 2, 3])` ➔ `[1, 2, 3]`                                               |
| `np.intersect1d()`    | Finds the intersection of two arrays (elements common to both).                                                                                                            | `np.intersect1d([1, 2, 3], [3, 4])` ➔ `[3]`                                           |
| `np.union1d()`        | Returns the union of two arrays (all unique elements from both arrays).                                                                                                    | `np.union1d([1, 2], [2, 3])` ➔ `[1, 2, 3]`                                            |
| `np.setdiff1d()`      | Returns the set difference, i.e., elements in the first array that are not in the second.                                                                                   | `np.setdiff1d([1, 2, 3], [2, 3])` ➔ `[1]`                                             |
| `np.setxor1d()`       | Returns the symmetric difference, i.e., elements that are in either of the arrays but not in both.                                                                         | `np.setxor1d([1, 2, 3], [2, 3, 4])` ➔ `[1, 4]`                                        |
| `np.in1d()`           | Checks if elements of one array are in another array, returns a boolean array of the same shape as the first array.                                                        | `np.in1d([1, 2, 3], [2, 3])` ➔ `[False, True, True]`                                  |
| `np.isin()`           | Similar to `np.in1d()` but works for arrays with any shape, returning an array of the same shape as the input with `True` or `False` for each element.                     | `np.isin([[1, 2], [3, 4]], [2, 3])` ➔ `[[False, True], [True, False]]`                 |
