In [2]:
import numpy as np

### ndarray object: 
n-dimensional array, is the fundamental data structure of the library.
##### Key Characteristics: 
    - homogeneous data type
    - shape and dimensions
    - memory efficiency and speed
    - mutable and indexable

In [3]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
data * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12]])

every array has a shape, a tuple indicating the size of each dimension & <br>
a dtype, an object describing the data type of the array

In [6]:
data.shape # shape of array


(2, 3)

In [7]:
data.dtype # data type of element in the array


dtype('int64')

In [8]:
data.size # total no of elements


6

In [9]:
data.ndim # no of dimensions

2

### creating ndarrays: 
| Method               | Description                                              |
|----------------------|----------------------------------------------------------|
| `np.array()`         | Creates array from list, tuple, or array-like object     |
| `np.zeros()`         | Array filled with zeros                                  |
| `np.ones()`          | Array filled with ones                                   |
| `np.full()`          | Array filled with a specific value                       |
| `np.empty()`         | Uninitialized array                                      |
| `np.arange()`        | Array with range of values                               |
| `np.linspace()`      | Array with evenly spaced values                          |
| `np.eye()`, `np.identity()` | Identity matrix                          |
| `np.random` module   | Array with random values, integers, or distributions     |
| `np.fromfunction()`  | Array from function applied to each coordinate           |
| `np.fromiter()`      | Array from iterable object                               |
| `np.reshape()`       | Reshape existing array into a new shape                  |

In [10]:
# np.array()
arr = np.array([1,2,3.3,4,5.6])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
arr

array([1. , 2. , 3.3, 4. , 5.6])

In [12]:
arr.dtype

dtype('float64')

In [13]:

arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2d.dtype

dtype('int64')

In [15]:
# np.zeros()
zeros_arr = np.zeros(3)
zeros_arr

array([0., 0., 0.])

In [16]:
zeros_arr2d = np.zeros((3,3))
zeros_arr2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# np.ones() -> similar to np.zeros()
ones_arr = np.ones(3)
ones_arr

array([1., 1., 1.])

In [18]:
ones_arr2d = np.ones((3,3))
ones_arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# np.full() -> creates an array with a specified shape, filled with a specific value
full_arr = np.full(3, 7)
full_arr

array([7, 7, 7])

In [20]:
full_arr2d = np.full((3,3), 7)
full_arr2d

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [21]:
# np.empty() -> Creates an array without initializing the values, which can be faster but contains random data. 
# Useful if you plan to overwrite the array later
empty_arr = np.empty((3,2))
empty_arr

array([[5.25937018e-310, 0.00000000e+000],
       [9.76118064e-313, 2.46151512e-312],
       [2.37663529e-312, 4.99006302e-322]])

In [22]:
# np.arange() -> generates values within a specified range with a given step
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [23]:
# np.linspace() -> generates an array with a specified number of evenly spaced values between a start and end value
linspace_arr = np.linspace(0, 1, 5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# np.eye() or np.identity()
eye_arr = np.eye(3)
eye_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
identity_arr = np.identity(2) # 2 x 2 identity matrix
identity_arr

array([[1., 0.],
       [0., 1.]])

In [26]:
# np.random module 

# np.random.rand() -> creates an array of given shape with random values btw 0 and 1
rand_arr = np.random.rand(4,3)
rand_arr

array([[0.69310197, 0.78247423, 0.85199221],
       [0.99598305, 0.04148243, 0.05361418],
       [0.02543371, 0.63734572, 0.50096671],
       [0.8878622 , 0.24223926, 0.09160172]])

In [27]:
# np.random.randint() -> array of random integers within a specified range
randint_arr = np.random.randint(0,10, (2,3)) # range 0 to 9, shape = (2,3)
randint_arr

array([[4, 2, 6],
       [3, 8, 7]])

In [28]:
# np.random.randn() -> array of random values drawn from a standard normal distribution ( mean 0, standard deviation 1)
# This standardization allows for easier comparison between different data sets that may have different means and standard deviations

randn_arr = np.random.randn(3)
randn_arr

array([ 0.39138586, -0.06618063, -0.45702062])

In [29]:
randn_arr2d = np.random.randn(2,3)
randn_arr2d

array([[1.12492106, 0.81432552, 1.23575176],
       [0.4989723 , 0.78079581, 2.19433684]])

In [31]:
# np.reshape() -> it reshapes an existing array into a new shape without modifying the original data
arr = np.arange(12)
reshaped_arr = arr.reshape((2,6))
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])