In [2]:
import numpy as np

 ### ndarrays attributes

In [3]:
# ndarray.shape
arr1 = np.array([1,2,3,4,5,6])
arr1.shape

(6,)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.shape

(2, 3)

In [5]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3.shape

(2, 2, 2)

In [6]:
# access the shape using .shape
# reshape an array by assigning a new shape using .reshape()
# total number of elements must remain the same
arr1_reshaped = arr1.reshape((3,2))
arr1_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# ndarray.size
arr1.size

6

In [8]:
arr2.size

6

In [9]:
arr3.size

8

In [10]:
# ndarray.ndim
arr1.ndim

1

In [11]:
arr2.ndim

2

In [12]:
arr3.ndim

3

In [20]:
# ndarray.dtype
# represents the data type of elements stored in the array
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1.1, 2.0, 3.0], dtype=np.float64)
arr_str = np.array(['a', 'b', 'c'], dtype=np.str_)

In [21]:
arr_int.dtype

dtype('int32')

In [22]:
arr_float.dtype

dtype('float64')

In [23]:
arr_str.dtype

dtype('<U1')

In [24]:
# can convert an array to a different data type using astype(), {creates a new array}
arr_float_to_int = arr_float.astype(np.int32)
arr_float_to_int

array([1, 2, 3], dtype=int32)

In [25]:
# itemsize : returns the size in bytes of each element in the array
arr_int.itemsize

4

In [26]:
# nbytes: returns total no of bytes consumed by the array
arr_int.nbytes

12

### dtypes for ndarrays
special object containing the info (data about data, metadata)


| **Data Type**         | **Description**                                      | **Example**                    |
|-----------------------|------------------------------------------------------|--------------------------------|
| **Integer Types**     |                                                      |                                |
| `np.int8`             | 8-bit signed integer                                 | `-128` to `127`                |
| `np.int16`            | 16-bit signed integer                                | `-32768` to `32767`            |
| `np.int32`            | 32-bit signed integer                                | `-2^31` to `2^31-1`            |
| `np.int64`            | 64-bit signed integer                                | `-2^63` to `2^63-1`            |
| `np.uint8`            | 8-bit unsigned integer                               | `0` to `255`                   |
| `np.uint16`           | 16-bit unsigned integer                              | `0` to `65535`                 |
| `np.uint32`           | 32-bit unsigned integer                              | `0` to `2^32-1`                |
| `np.uint64`           | 64-bit unsigned integer                              | `0` to `2^64-1`                |
| **Floating-Point Types** |                                                  |                                |
| `np.float16`          | 16-bit half precision floating-point                 |                                |
| `np.float32`          | 32-bit single precision floating-point               |                                |
| `np.float64`          | 64-bit double precision floating-point               |                                |
| **Complex Number Types** |                                                |                                |
| `np.complex64`        | Complex number represented by two 32-bit floats      |                                |
| `np.complex128`       | Complex number represented by two 64-bit floats      |                                |
| **Boolean Type**      |                                                      |                                |
| `np.bool_`            | Boolean (True or False)                              | `True`, `False`                |
| **String Types**      |                                                      |                                |
| `np.str_`             | Unicode string with variable length                  | `"hello"`                      |
| `np.unicode_`         | Alias for `np.str_`, represents Unicode text         | `"こんにちは"`                 |
| `np.string_`          | Fixed-width ASCII string (bytes)                     | `b"hello"`                     |
| `np.bytes_`           | Alias for `np.string_`, for binary (byte) strings    | `b"data"`                      |
| **Object Type**       |                                                      |                                |
| `np.object_`          | General Python objects                               | Any Python object              |
| **Datetime Types**    |                                                      |                                |
| `np.datetime64`       | Dates in ISO format (e.g., `YYYY-MM-DD`)             | `np.datetime64('2023-01-01')`  |
| **Timedelta Types**   |                                                      |                                |
| `np.timedelta64`      | Time duration (difference between dates)             | `np.timedelta64(5, 'D')`       |

### Key Notes:
- `np.str_` and `np.unicode_` represent Unicode strings, while `np.string_` is specifically for ASCII strings.
- `np.bytes_` and `np.string_` store fixed-width byte-encoded strings.
- `np.datetime64` and `np.timedelta64` are useful for date-time computations and time intervals.


data types helps for interacting with data coming from other systems. <br>
they provide a mapping directly onto an underlying disk or memory representation, which makes it possible to read and write binary streams of data to disk & to connect the code written in C or FORTAN <br>
signed integer can represent both positive and negative integers <br>
unsigned integer can only represent nonzero integers

In [27]:
# explicitly casting
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [28]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3.])

In [31]:
arr = np.array([1.3, 4.56, -68.2])
arr.astype(np.int32) # decimal part will be truncated


array([  1,   4, -68], dtype=int32)

In [34]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
# using another array's dtype attribute
int_array = np.arange(10)
calibers = np.array([2.2, -3.4])
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

calling `astype` always create new array 