In [143]:
import numpy as np

In [144]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [145]:
1 / arr 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [146]:
arr ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [147]:
# comparison btw arrays of the same size yeild Boolean Arrays: 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [148]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

evaluating operations btw differently sized arrays is called **broadcasting**

#### element wise arithmetic

In [149]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [150]:
a + b

array([5, 7, 9])

In [151]:
a - b

array([-3, -3, -3])

In [152]:
a * b

array([ 4, 10, 18])

In [153]:
a / b 

array([0.25, 0.4 , 0.5 ])

#### scalar operations

In [154]:
a = np.array([1,2,3])

In [155]:
a + 5

array([6, 7, 8])

In [156]:
a * 2

array([2, 4, 6])

#### unary operations
involve performing fns on individual elements of a single array

In [157]:
a = np.array([-1,0,-3,4])

In [158]:
np.abs(a) # absolute value

array([1, 0, 3, 4])

In [159]:
a.sum()

np.int64(0)

In [160]:
a.mean()

np.float64(0.0)

In [161]:
a.max()

np.int64(4)

In [162]:
a.min()

np.int64(-3)

#### matrix multiplication

In [163]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [164]:
a @ b # matrix multiplication {dot product}

array([[19, 22],
       [43, 50]])

In [165]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

#### aggregate functions
sum,mean,std(standard deviation),var(variance), min,max,argmin,argmax,prod(productof elements)

In [166]:
a = np.array([1,2,3,4])

In [167]:
a.std()

np.float64(1.118033988749895)

In [168]:
a.var()

np.float64(1.25)

In [169]:
a.argmin()

np.int64(0)

In [170]:
a.argmax()

np.int64(3)

#### comparison operations

In [171]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
a > b

array([False, False,  True])

In [172]:
a == b

array([False,  True, False])

#### logical operations
Logical operations like `np.logical_and`, `np.logical_or`, and `np.logical_not` combine Boolean arrays

In [173]:
a = np.array([True, False, True])
b = np.array([False, False, True])

In [174]:

np.logical_and(a, b)


array([False, False,  True])

In [175]:

np.logical_or(a, b)

array([ True, False,  True])

In [176]:
np.logical_not(a)

array([False,  True, False])

#### trigonometric functions
np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan

In [177]:
angles = np.array([0, np.pi / 2, np.pi])
np.sin(angles)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [178]:
np.cos(angles)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

#### exponent and logarithmic functions
np.log, np.log10, np.log2

In [179]:
a = np.array([1,2,3])
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [180]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125])

#### rounding functions
np.floor, np.ceil, np.round

In [181]:
a = np.array([1.5,2.3,3.8])
np.floor(a)

array([1., 2., 3.])

In [182]:
np.ceil(a)

array([2., 3., 4.])

In [183]:
np.round(a)

array([2., 2., 4.])

## some advanced operations

#### bitwise operations
`itwise_and`, `bitwise_or`, `bitwise_xor`, `invert`, `left_shift`, and `right_shift` on integer arrays

#### set operations
`np.union1d`, `np.intersect1d`,`np.setdiff1d`, and `np.setxor1d`

In [185]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [186]:
np.intersect1d(a,b)

array([3, 4])

#### statistical operations
`np.median`, `np.percentile`, `np.corrcoef`(corelation), `np.cov`(covariance), `np.histogram`

In [187]:
data = np.array([1,2,2,3,4,5,5,6])
np.median(data)

np.float64(3.5)

#### linear algebra operations
#### advanced array manipulation operations
#### ragged array operations
#### broadcasting operations