In [141]:
import numpy as np

In [142]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
arr[5:8]

array([5, 6, 7])

In [144]:
arr[-7:-3]

array([3, 4, 5, 6])

In [145]:
arr[5:8] = 12 # assign a scalar value to a slice
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

note:
 - array slices are views on the original array <br>
 - means the data is not copied <br>
 - modifications will be reflected in the source array <br>
arr[x:y].copy() -> explicitly copy the array

In [146]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [147]:
arr_slice[1] = 1234
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [148]:
# [:] will assign to the values in an array
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [149]:
sslice = arr[1:3].copy()
sslice

array([1, 2])

In [150]:
sslice[:] = 99
sslice

array([99, 99])

In [151]:
arr # no change by sslice

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### higher dimensional arrays

In [152]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0] # elements at each index are no longer scalars

array([1, 2, 3])

In [153]:
arr2d[0][2] # second indexed element of zeroth index of arr2d

np.int64(3)

In [154]:
arr2d[0,2]

np.int64(3)

In [155]:
arr2d[0][2] == arr2d[0,2]

np.True_

In [156]:
# 3d array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [157]:
arr3d[0] # a 2 × 3 array

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
arr3d[0][1][2]

np.int64(6)

In [159]:
arr3d[0,1,2]

np.int64(6)

In [160]:
# both scalar values and arrays can be assigned to arr3d[0]
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [161]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [162]:
arr3d[1,1]
# NOTE that in all of these cases where subsections of the array have been selected, the returned array are views

array([10, 11, 12])

In [163]:
arr3d[::-1]

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

### Indexing with slices

In [164]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [165]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [166]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [168]:
# passing multiple slices
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [169]:
# select the second row but only the first two columns:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [170]:
lower_dim_slice.shape

(2,)

In [171]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [172]:
# assign to a slice
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [173]:
arr2d[::-1, ::-1]

array([[9, 8, 7],
       [0, 0, 4],
       [0, 0, 1]])

In [174]:
arr2d[::2, ::2]

array([[1, 0],
       [7, 9]])

### Boolean Indexing

In [175]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [176]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [177]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [178]:
# suppose each name corresponding to a row in the data array
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [179]:
# boolean array must be of the same length as the array axis it's indexing
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [180]:
# slicing
data[names == "Bob", 1:] # 1: selects all columns from index 1 (the second column) onward
# returns a 2D array

array([[7],
       [0]])

In [181]:
data[names == "Bob", 1] # 1 selects only the column at index 1 (the second column)
# returns a 1D array

array([7, 0])

To select everything but "Bob" you can either use != or negate the condition using ~


In [182]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [183]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [184]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In NumPy, the ~ operator is used to invert a Boolean array. <br>
When applied to a Boolean array, it flips True values to False and False values to True. <br>
This is especially useful when filtering or selecting parts of an array based on the inverse of a condition.

In [185]:
cond = names == "Bob" # using a separate variable to store the condition can make code clearer, reusable, & easier to maintain
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

To select multiple name to combine Boolean conditions, use boolean arithmetic operators: 
& (and) , | (or)

In [186]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [187]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

NOTE: selecting data from an array by boolean indexing and assigning the result to a new variable always creates a copy of the data, even if the returned array is unchanged

Boolean Masking: manipulate arrays based on certain conditions <br>
It involves creating a boolean array(mask) that indicates which elements of the original array satisfy a specific condition

In [188]:
data[data < 0] = 0 # indexing with the boolean mask ~~ selects all elements in data that are less than zero
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [189]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

#### Fancy Indexing
describe indexing using integer arrays

In [190]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i
arr 

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

to select a subset of the rows in a particular order, simply pass a list or ndarray of integers specifying the desired order: 

In [191]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [192]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

passing multiple index arrays does slightly different

In [193]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [194]:
arr[[1,5,7,2],[0,3,1,2]]
# elements (1, 0), (5, 3), (7, 1), and (2, 2) are selected

array([ 4, 23, 29, 10])

In [195]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # don't know how happened !

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

fancy indexing, unlike slicing, always copies the data into a new array when assigning the result to a new variable.

In [196]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

### Transposing Arrays & Swapping Axes
special form of reshaping that similarly returns a view on the underlying data without copying anything 

In [197]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [198]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

when doing matrix computations / when computing the inner matrix product using numpy.dot

In [199]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [200]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [201]:
np.dot(arr.T,arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [202]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

simple transposing with .T is a special case of swapping axes. <br>
ndarray has the method `swapaxes`, which takes a pair of axis numbers and switches the indicated axes to rearrange the data:

In [203]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [204]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

swapaxes similarly returns a view on the data without making a copy