In [15]:
import numpy as np

reshape() doesn't modify the original array but returns a new one

In [16]:
arr = np.array([1,2,3,4,5,6])
# arr.reshape((2,3))

resize() modifies the array in place

In [17]:
arr2 = arr.resize((2,3))
arr


array([[1, 2, 3],
       [4, 5, 6]])

reshape(-1) automatically calculates that dimension based on the total no of elements

In [18]:
arr = np.array([1,2,3,4,5,6])
arr.reshape((3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

flatten() converts a multi-dimensional array into a 1D array

In [21]:
arr = np.array([[1,2,3],[4,5,6]])
arr.flatten()

array([1, 2, 3, 4, 5, 6])

ravel() also flattens but returns a view if possible <br>
meaning any changes to the returned array may affect the original array

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.ravel()

array([1, 2, 3, 4, 5, 6])