In [2]:
import numpy as np

### stacking arrays

np.concatenate() combine arrays along its existing axis <br>
the arrays must have same shape along the concatenation axis

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a,b), axis=0)  

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

np.vstack() stacks arrays vertically ( row wise )

In [5]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

np.hstack() stack arrays horizontally ( col wise )

In [6]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

np.dstack() stack arrays along a new depth ( third ) axis

In [7]:
np.dstack((a,b))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

np.column_stack() stacks 1D array as colns into a 2D array <br>
if the input are 2D arrays, it behaves like hstack()

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

np.row_stack() stack arrays in sequence vertically, row-wise, and behaves similarly to vstack()

In [9]:
np.row_stack((a,b))

/tmp/ipykernel_1323/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

np.stack() stacks arrays along a new axis, which is specified with the axis argument <br>
all input arrays must have same shape

In [10]:
np.stack((a,b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

### splitting arrays

np.split() splits an array into multiple sub-arrays along a specified axis <br>
you provide indices where the splits should occur

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.split(arr, 3, axis=0) # split into 3 equal parts along rows

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [13]:
np.split(arr, [1,2], axis=1) # split at columns 1 & 2

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

np.vsplit() splits an array vertically (row-wise) - {np.split with axis=0}

In [14]:
np.vsplit(arr,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

np.hsplit() splits an array vertically (col-wise) - {np.split with axis=1}

In [15]:
np.hsplit(arr,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

no.dsplit() splits an array along the depth (3rd axis), only applied on 3D arrays

In [18]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
np.dsplit(arr_3d, 2)

[array([[[1],
         [3]],
 
        [[5],
         [7]]]),
 array([[[2],
         [4]],
 
        [[6],
         [8]]])]