### **Universal functions (ufuncs)**:
- are highly optimized functions in NumPy that perform element-wise operations on arrays
- enable you to apply mathematical functions across all elements of an array without using explicit loops

#### Types of Universal Functions:
- Unary Ufuncs: operate on a single array performing an operation on each element
- Binary Ufuncs: operate on two arrays element wise, usually performing arithmetic or comparison operations

In [3]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
rng = np.random.default_rng(seed=12345)

In [9]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)

In [10]:
x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [11]:
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [13]:
np.maximum(x,y) # element-wise maximum of the elements in x and y

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

**numpy.modf**: a ufunc that can return multiple arrays
- a vectorized version of the built-in Python math.modf
- it returns the fractional and integral parts of a floating-point array

In [14]:
arr = rng.standard_normal(7) * 5
arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [15]:
remainder, whole_part = np.modf(arr)

In [16]:
remainder

array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
       -0.49849258,  0.51459671])

In [17]:
whole_part

array([ 3., -6.,  2.,  6.,  6., -1.,  4.])

**NOTE**: 
- ufuncs provide an optional `out` argument that allows you to specify an existing array to store the result of the operation.
- helpful when want to save memory by reusing an existing array rather than creating a new one

In [22]:
# original array
arr = np.array([4.5146, -8.1079, -0.7909, 2.2474, -6.718, -0.4084, 8.6237])

# creating an output array 
output = np.zeros_like(arr) # creates an array with the same shape as arr but filled with zeros

np.add(arr,1) # returns a new array with the result
# without specifying "out", a new array is created to hold this result

array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [23]:
# using np.add with out argument
np.add(arr,1, out=output) # we directly tell to store the result into the output array rather than creating a new array

array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [25]:
output

array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

difference: 
- `np.add(arr, 1, out=output)`: stores the result directly in the pre-existing `output` array
- `output = np.add(arr, 1)`: creates a new array to store the result and assigns it to `output`



---

### Table . Some Unary Universal Functions

| Function                 | Description                                                                                                                |
|--------------------------|----------------------------------------------------------------------------------------------------------------------------|
| `abs`, `fabs`            | Compute the absolute value element-wise for integer, floating-point, or complex values                                     |
| `sqrt`                   | Compute the square root of each element (equivalent to `arr ** 0.5`)                                                       |
| `square`                 | Compute the square of each element (equivalent to `arr ** 2`)                                                              |
| `exp`                    | Compute the exponent \( e^x \) of each element                                                                             |
| `log`, `log10`, `log2`, `log1p` | Natural logarithm (base \( e \)), log base 10, log base 2, and log(1 + x), respectively                               |
| `sign`                   | Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)                                                 |
| `ceil`                   | Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)                      |
| `floor`                  | Compute the floor of each element (i.e., the largest integer less than or equal to each element)                           |
| `rint`                   | Round elements to the nearest integer, preserving the dtype                                                                |
| `modf`                   | Return fractional and integral parts of array as separate arrays                                                           |
| `isnan`                  | Return Boolean array indicating whether each value is NaN (Not a Number)                                                   |
| `isfinite`, `isinf`      | Return Boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively                |
| `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions                                                       |
| `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions                                                  |
| `logical_not`            | Compute truth value of not x element-wise (equivalent to `~arr`)                                                           |

---

### Table . Some Binary Universal Functions

| Function                  | Description                                                                                                            |
|---------------------------|------------------------------------------------------------------------------------------------------------------------|
| `add`                     | Add corresponding elements in arrays                                                                                   |
| `subtract`                | Subtract elements in second array from first array                                                                     |
| `multiply`                | Multiply array elements                                                                                                |
| `divide`, `floor_divide`  | Divide or floor divide (truncating the remainder)                                                                      |
| `power`                   | Raise elements in first array to powers indicated in second array                                                     |
| `maximum`, `fmax`         | Element-wise maximum; `fmax` ignores NaN                                                                              |
| `minimum`, `fmin`         | Element-wise minimum; `fmin` ignores NaN                                                                              |
| `mod`                     | Element-wise modulus (remainder of division)                                                                          |
| `copysign`                | Copy sign of values in second argument to values in first argument                                                    |
| `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Perform element-wise comparison, yielding Boolean array (equivalent to infix operators `>`, `>=`, `<`, `<=`, `==`, `!=`) |
| `logical_and`             | Compute element-wise truth value of AND (`&`) logical operation                                                        |
| `logical_or`              | Compute element-wise truth value of OR (`|`) logical operation                                                        |
| `logical_xor`             | Compute element-wise truth value of XOR (`^`) logical operation                                                       |

---
