### Aggregate Functions: 
- reduce an array to a single value or to a lower dimensional summary
- perform operations across specified axes to produce summary values
### Key Aggregate Functions



| Function           |Description                                                                                           |
|--------------------|-------------------------------------------------------------------------------------------------------|
| `sum`              | Computes the sum of all elements in the array or along a specified axis.                              |
| `mean`             | Calculates the mean (average) of all elements or along an axis.                                       |
| `std`              | Computes the standard deviation of elements, showing how much variation or spread there is from the mean. |
| `var`              | Computes the variance of elements, representing the average of the squared deviations from the mean.  |
| `min`              | Finds the minimum value in the array or along a specified axis.                                       |
| `max`              | Finds the maximum value in the array or along a specified axis.                                       |
| `argmin`           | Returns the index of the minimum value in the array or along an axis.                                 |
| `argmax`           | Returns the index of the maximum value in the array or along an axis.                                 |
| `cumsum`           | Returns the cumulative sum of elements, with each element representing the sum up to that position.   |
| `cumprod`          | Returns the cumulative product of elements, with each element representing the product up to that position. |
| `median`           | Computes the median (middle value) of elements in the array.                                         |
| `percentile`       | Computes the nth percentile, which gives a value below which a specified percentage of elements fall. |
| `prod`             | Calculates the product of all elements in the array or along a specified axis.                       |


In [2]:
import numpy as np

In a multi-dim array: 
- Axis 0 = rows direction ( moving vertically)
- Axis 1 = cols direction ( moving horizontally )

In [3]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

np.sum(arr, axis=0) # computed down the rows, means calculated across each column

array([15, 18, 21, 24])

In [4]:
np.sum(arr, axis=1) # computed across the cols, means calculated for each row

array([10, 26, 42])

In [5]:
# if no axis specified
np.sum(arr) # apply to all elements

np.int64(78)

In [8]:
print(np.mean(arr, axis=0))
print(np.max(arr, axis=1))
print(np.cumsum(arr, axis=1)) # cumulative sum

[5. 6. 7. 8.]
[ 4  8 12]
[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]


In [9]:
# 3D arrays
arr_3d = np.array([
    [[ 1,  2,  3,  4],
     [ 5,  6,  7,  8],
     [ 9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])


In [10]:
np.sum(arr_3d, axis=0) # depth

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [11]:
np.sum(arr_3d, axis=1) # down the rows

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [12]:
np.sum(arr_3d, axis=2) # across the cols

array([[10, 26, 42],
       [58, 74, 90]])