# Broadcasting
It governs how operations work btw arrays of diff shapes. <br>
Arithmetic operations on arrays are usually done on corresponding elements. <br>
The smaller array is broadcasted to the size of the larger array so that they have compatible shapes. <br>
It can be a powerful feature, but it can cause confusion, even for experienced users.<br>
The simplest example occurs when combining a scalar value with an array

In [2]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
arr * 4 # Here we say that the scalar value 4 has been broadcast to all of the other elements in the multiplication operation

array([ 0,  4,  8, 12, 16])

In [5]:
arr = np.random.standard_normal((4,3))
print(arr)

arr.mean(0)

[[ 0.59720965  0.15558933  0.47851353]
 [ 0.51880856  1.254721    0.54668618]
 [ 0.01631175 -1.6402958   1.40909135]
 [-1.45996078 -0.53783878 -0.32297761]]


array([-0.08190771, -0.19195606,  0.52782836])

In [6]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 0.67911736,  0.34754539, -0.04931483],
       [ 0.60071627,  1.44667706,  0.01885782],
       [ 0.09821945, -1.44833974,  0.88126298],
       [-1.37805308, -0.34588271, -0.85080597]])

###  np.newaxis()
allow to increase the dimensions of an existing array. <br>
commonly used to reshape arrays for various operations, particularly in the context of broadcasting

In [16]:
# Converting a 1D Array to a 2D Column Vector

# Create a 1D array
a = np.array([0, 1, 2, 3, 4])
print(a.shape)

# Convert to a column vector
column_vector = a[:, np.newaxis]
print(column_vector)
print(column_vector.shape)

(5,)
[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [17]:
# Convert to a row vector
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4]]
(1, 5)


In [18]:
# Adding Multiple Dimensions

multi_dimensional = a[np.newaxis, :, np.newaxis]
print(multi_dimensional)
print(multi_dimensional.shape)

[[[0]
  [1]
  [2]
  [3]
  [4]]]
(1, 5, 1)


### Setting Array Values by Broadcasting

In [10]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [11]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis] # col
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [19]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])