many NumPy users will only use the fast element-wise operations provided by the universal functions, a number of additional features occasionally can help you write more concise code without explicit loops

In [1]:
import numpy as np

### ufunc Instance Methods
Each of NumPy’s binary ufuncs has special methods for performing certain kinds of
special vectorized operations

In [3]:
''' 
reduce takes a single array and aggregates its values, optionally along an axis, by performing a sequence of binary operations
''' 

# ex: alt way to sum elements in an array : use np.add.reduce

arr = np.arange(10)
print(np.add.reduce(arr))
print(arr.sum())

45
45



1. **`np.add.reduce(arr)`**:
   - This uses the `reduce` operation with the `np.add` function, which applies the addition operation cumulatively along the specified axis.
   - This function is slightly more flexible because you can replace `np.add` with other operations (e.g., `np.multiply.reduce` to get the product of elements).
   - Usage: `np.add.reduce(arr, axis=...)`

2. **`arr.sum()`**:
   - This is a shorthand method for summing elements in a NumPy array, typically more convenient and readable for summation.
   - It’s optimized for summing elements and is equivalent to `np.add.reduce(arr)` for summing, though `arr.sum()` may be preferred in terms of readability.
   - Usage: `arr.sum(axis=...)`

## .reduce in clear words: 
What .reduce Does

Think of .reduce as asking:
- "How can I combine all elements in this array with a specific operation (e.g., adding, multiplying, or applying a logical AND)?"

The .reduce function takes an operation (like np.add, np.multiply, np.logical_and, etc.) and applies it across the elements of an array. It does this in pairs, one at a time, until a single result is produced.
Example 1: Sum of Elements with np.add.reduce

Imagine we have an array:

```python
arr = np.array([1, 2, 3, 4])
```

If we apply np.add.reduce(arr), it will add the elements one by one from left to right, as follows:

Start with the first two elements: 1 + 2 = 3 <br>
Take the result (3) and add the next element: 3 + 3 = 6<br>
Take the result (6) and add the last element: 6 + 4 = 10<br>

So, np.add.reduce(arr) will return 10.<br>

In general:
- np.add.reduce takes all elements and reduces them to a single result by adding.



**Reducing Along an Axis in 2D Arrays**

When you have a 2D array, .reduce can work along rows or columns. For instance:

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
```

If we use np.add.reduce(arr, axis=0), it will sum down each column:

First column: 1 + 4 + 7 = 12<br>
Second column: 2 + 5 + 8 = 15<br>
Third column: 3 + 6 + 9 = 18<br>

The result will be [12, 15, 18].<br>

If we use np.add.reduce(arr, axis=1), it will sum across each row:

First row: 1 + 2 + 3 = 6<br>
Second row: 4 + 5 + 6 = 15<br>
third row: 7 + 8 + 9 = 24<br>

The result will be [6, 15, 24].

### **Why .reduce is Useful**

.reduce is useful when you need to combine elements in a sequence according to a rule, such as summing, multiplying, or checking if all elements meet a condition. By using .reduce with different operations (like np.add, np.multiply, or np.logical_and), you can apply various kinds of cumulative processing to arrays.


**Another Example: Checking if All Elements are Increasing**

Let’s say we want to check if every element in an array is less than the next element, which is what you were looking at earlier with np.logical_and.reduce.

```python
arr = [1, 2, 3, 4]
```

If we write 
```python 
np.logical_and.reduce(arr[:-1] < arr[1:])
``` 
, it will:

Check if each element is less than the next one `(arr[:-1] < arr[1:] gives [True, True, True])`.
Combine all the results with a logical AND:
    - True AND True = True
    - True AND True = True

The final result is True, meaning all elements are indeed increasing.

But if arr were [1, 2, 4, 3], then:

arr[:-1] < arr[1:] would be [True, True, False]<br>
np.logical_and.reduce([True, True, False]) would yield False (since not all comparisons were True).

In [5]:
my_rng = np.random.default_rng(12346) # for reproducibility
arr = my_rng.standard_normal((5, 5))
arr

array([[-0.903889  ,  0.15713146,  0.89761199, -0.76219554, -0.17625556],
       [ 0.05303172, -1.62844028, -0.17753333,  1.96360352,  1.78125478],
       [-0.87971984, -1.69847913, -1.81891091,  0.11895453, -0.44409513],
       [ 0.76911421, -0.03433778,  0.39252776,  0.75891811, -0.07045967],
       [ 1.04984775,  1.02967072, -0.42005533,  0.78626627,  0.96124929]])

In [7]:
arr[::2].sort(1) # sort row 0,2,4
arr

array([[-0.903889  , -0.76219554, -0.17625556,  0.15713146,  0.89761199],
       [ 0.05303172, -1.62844028, -0.17753333,  1.96360352,  1.78125478],
       [-1.81891091, -1.69847913, -0.87971984, -0.44409513,  0.11895453],
       [ 0.76911421, -0.03433778,  0.39252776,  0.75891811, -0.07045967],
       [-0.42005533,  0.78626627,  0.96124929,  1.02967072,  1.04984775]])

In [9]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [12]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1) # checks if all comparisons in each row are True

array([ True, False,  True, False,  True])

## accumulate ufunc method 
is related to reduce, like cumsum is related to sum <br>
It produces an array of the same size with the intermediate "accumulated" values

In [13]:
arr = np.arange(15).reshape((3,5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [16]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [17]:
np.multiply.outer(arr, np.arange(5)) # outer performs a pair-wise cross product btw two arrays

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [19]:
# output of the outer will have a dimension that is the concatenation of the dimensions of the inputs
x, y = my_rng.standard_normal((3,4)), my_rng.standard_normal(5)
result = np.subtract.outer(x,y)
result.shape

(3, 4, 5)

### reduceat 
 Instead of applying an operation (like sum or multiply) across the entire array or along a single axis, reduceat applies the operation at specific sections of the array, as defined by a list of indices

In [24]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
np.add.reduceat(arr, [3, 5, 8])

array([ 7, 18, 17])

In [26]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
print(arr)

np.add.reduceat(arr, [0,2,4], axis=1)

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]]


array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

## Writing New ufuncs in Python
There are no of ways to do it. The most general is to use the NumPy C API. <br>
But we will look at pure Python ufuncs - 

`numpy.frompyfunc` accepts a python function along with a specification for the number of inputs and outputs.

In [27]:
# for ex: a simple fn that adds element-wise would be specified as:
def add_elements(x,y):
    return x + y 

add_them = np.frompyfunc(add_elements, 2, 1)

add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

Functions created using frompyfunc always return arrays of Python objects, which
can be inconvenient.<br> 
Fortunately, there is an alternative (but slightly less feature rich)
function, `numpy.vectorize`, that allows you to specify the output type

In [28]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

These functions provide a way to create ufunc-like functions, but they are very slow because they require a Python function call to compute each element, which is a lot slower than NumPy’s C-based ufunc loops

In [30]:
arr = my_rng.standard_normal(10000)
%timeit add_them(arr, arr)

3.48 ms ± 227 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
%timeit np.add(arr,arr)

8.35 μs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
