In [10]:
import numpy as np

# the ndarray sort instance method is an in-place sort, meaning that the array contents are rearranged without producing a new array
# when sorting arrays in place, remember that if the array is a view on a different ndarray, the original array will be modified

rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal(5)
arr.sort
arr

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [11]:
arr = rng.standard_normal((3,5))
arr

array([[-0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306],
       [ 2.34740965,  0.96849691, -0.75938718,  0.90219827, -0.46695317],
       [-0.06068952,  0.78884434, -1.25666813,  0.57585751,  1.39897899]])

In [12]:
arr[:, 0].sort() # sort first column values in place
arr

array([[-0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306],
       [-0.06068952,  0.96849691, -0.75938718,  0.90219827, -0.46695317],
       [ 2.34740965,  0.78884434, -1.25666813,  0.57585751,  1.39897899]])

In [13]:
# numpy.sort creates a new, sorted copy of an array
arr = rng.standard_normal(5)
arr

array([ 1.32229806, -0.29969852,  0.90291934, -1.62158273, -0.15818926])

In [15]:
print(np.sort(arr))
print(arr)

[-1.62158273 -0.29969852 -0.15818926  0.90291934  1.32229806]
[ 1.32229806 -0.29969852  0.90291934 -1.62158273 -0.15818926]


In [16]:
# All of these sort methods take an axis argument for independently sorting the sections of data along the passed axis
arr = rng.standard_normal((3,5))
arr

array([[ 0.44948393, -1.34360107, -0.08168759,  1.72473993,  2.61815943],
       [ 0.77736134,  0.8286332 , -0.95898831, -1.20938829, -1.41229201],
       [ 0.54154683,  0.7519394 , -0.65876032, -1.22867499,  0.25755777]])

In [18]:
arr.sort(axis=1)
arr

array([[-1.34360107, -0.08168759,  0.44948393,  1.72473993,  2.61815943],
       [-1.41229201, -1.20938829, -0.95898831,  0.77736134,  0.8286332 ],
       [-1.22867499, -0.65876032,  0.25755777,  0.54154683,  0.7519394 ]])

In [19]:
# descending order
arr[:, ::-1]

array([[ 2.61815943,  1.72473993,  0.44948393, -0.08168759, -1.34360107],
       [ 0.8286332 ,  0.77736134, -0.95898831, -1.20938829, -1.41229201],
       [ 0.7519394 ,  0.54154683,  0.25755777, -0.65876032, -1.22867499]])

## Indirect Sorts: argsort and lexsort
Indirect sorts are techniques where we don't sort the actual data directly, but instead return indices that can be used to reorder the data

In [20]:
# np.argsort
# purpose: returns the indices that would sort the array
# how it works: it computes the permutation of indices required to sort the array

arr = np.array([50, 20, 30, 10])

# Get the indices that would sort the array
indices = np.argsort(arr)
print("Indices:", indices) 

# Use these indices to sort the array
sorted_arr = arr[indices]
print("Sorted Array:", sorted_arr) 


Indices: [3 1 2 0]
Sorted Array: [10 20 30 50]


In [21]:
# np.lexsort
# purpose: performs an indirect sort using multiple keys
# how it works: it sorts data lexicographically, starting from the last key provided

# Create two keys: last names and first names
last_names = np.array(['Smith', 'Jones', 'Williams', 'Smith'])
first_names = np.array(['John', 'Adam', 'Eve', 'Anna'])

# Perform a lexicographical sort
indices = np.lexsort((first_names, last_names))
print("Indices:", indices)  # Output: [1 3 0 2]

# Use indices to reorder data
sorted_last_names = last_names[indices]
sorted_first_names = first_names[indices]
print("Sorted Names:")
print(sorted_last_names)   
print(sorted_first_names)  


Indices: [1 3 0 2]
Sorted Names:
['Jones' 'Smith' 'Smith' 'Williams']
['Adam' 'Anna' 'John' 'Eve']


In [28]:
# combined example 

# Create some data
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
ages = np.array([25, 30, 25, 35])
scores = np.array([90, 85, 95, 88])

# Sort by age, then by score (descending)
indices = np.lexsort((-scores, ages))  # '-' for descending order
print("Sorted Indices:", indices)  # Output: [2 0 1 3]

# Reorder the data
sorted_names = names[indices]
sorted_ages = ages[indices]
sorted_scores = scores[indices]
print("Sorted Data:")
print("Names:", sorted_names)   
print("Ages:", sorted_ages)    
print("Scores:", sorted_scores) 

# list(zip(names[indices], ages[indices], scores[indices]))


Sorted Indices: [2 0 1 3]
Sorted Data:
Names: ['Charlie' 'Alice' 'Bob' 'David']
Ages: [25 25 30 35]
Scores: [95 90 85 88]


# Stable Sort Algorithm
- maintains the relative order of equal elements in the original array after sorting
- means that if two elements are equal in value, their order in the sorted array will be the same as their order in the input
#### Why Stability Matters
- in preserving original order
- combining multiple sorts

Example: bubble sort, insertion sort, merge sort, TimSort

# Partially Sorting Arrays
NumPy has fast methods, numpy.partition and np.argpartition, for partitioning an array around the k-th smallest element

In [24]:
rng = np.random.default_rng(12345)
arr = rng.standard_normal(20)
arr

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,
        2.34740965,  0.96849691, -0.75938718,  0.90219827, -0.46695317,
       -0.06068952,  0.78884434, -1.25666813,  0.57585751,  1.39897899])

In [25]:
# np.partition reorders the array so that the k smallest elements are on the left, and the remaining elements are on the right
np.partition(arr, 3) 
# the first 3 element in the result are the smallest three values in no particular order.

array([-1.95286306, -1.42382504, -1.3677927 , -1.25666813, -0.87066174,
       -0.75938718, -0.74088465, -0.46695317, -0.25917323, -0.07534331,
       -0.06068952,  0.36105811,  0.57585751,  0.6488928 ,  0.78884434,
        0.90219827,  0.96849691,  1.26372846,  1.39897899,  2.34740965])

In [26]:
# np.argpartition returns the indices of the array as if it were partially sorted
# useful when you want to retrive the smallest or largest elements without modifying the original array
indices = np.argpartition(arr, 3)
indices

array([ 9,  0,  6, 17,  2, 12,  5, 14,  3,  4, 15,  8, 18,  7, 16, 13, 11,
        1, 19, 10])

# numpy.searchsorted: Finding Elements in a Sorted Array
searchsorted is an array method that performs a binary search on a sorted array, returning the location in the array where the value would need to inserted to maintain sortedness

In [29]:
arr = np.array([0,1,7,12,15])
arr.searchsorted(9)

np.int64(3)

In [30]:
# You can also pass an array of values to get an array of indices back:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5])

In [31]:
# You might have noticed that searchsorted returned 0 for the 0 element. 
# This is because the default behavior is to return the index at the left side of a group of equal values
arr = np.array([0,0,0,1,1,1,1])
arr.searchsorted([0,1])

array([0, 3])

In [33]:
arr.searchsorted([0,1], side='right')

array([3, 7])