In [19]:
# importing the core library
import numpy as np

import os
for dirname, _, filenames in os.walk('../'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
# print multiple output in single cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

../50q-kaggle/1.ipynb


exercise 1: import numpy as np and see the version

In [20]:
np.__version__

'2.0.2'

exercise 2: how to create a 1D array?

In [21]:
# Question : Create a 1D array of numbers from 0 to 9
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

exercise 3: how to create a boolean array?

In [22]:
# Question : Create a 3×3 numpy array of all True’s
np.ones((3,3), dtype=bool)

np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

exercise 4: how to extract items that satisfy a given condition from 1D array?

In [56]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = np.arange(10)
arr%2==1
arr[arr%2==1]

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

array([1, 3, 5, 7, 9])

exercise 5: how to replace items that satisfy a condition with another value in numpy array?

In [24]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

exercise 6: how to replace items that satisfy a condition without affecting the original array?

In [27]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = np.arange(10)
arr_copy = arr.copy()
arr_copy[arr_copy%2 == 1] = -1

print("initial array: ",arr)
print("modified array: ", arr_copy)

initial array:  [0 1 2 3 4 5 6 7 8 9]
modified array:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


exercise 7: how to reshape an array?

In [28]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
  
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

exercise 8: how to stack two arrays vertically?

In [32]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,- 1)
b = np.repeat(1,10).reshape(2,-1) # repeat 1, 10 times

np.vstack([a, b]) # vertical stack | 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

exercise 9: how to stack two arrays horizontally?

In [33]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a, b]) # horizontal stack | 

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

exercise 10: how to generate custom sequences in numpy without hardcoding?

In [38]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# soln 1
a = np.array([1,2,3])
part1 = np.repeat(a,3)
part2 = np.tile(a,3)

np.concatenate([part1, part2])

# soln 2
np.r_[np.repeat(a, 3), np.tile(a, 3)]

# - np.r_ provides a concise way to concatenate arrays without explicitly calling np.concatenate.
# - It's especially useful for quick array manipulations, making code more compact


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

example 11: how to get the common items between two python numpy arrays?

In [40]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

exercise 12: how to remove from one array those items that exist in another?

In [44]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)  # set operations

array([1, 2, 3, 4])

exercise 13: how to get the positions where elements of two arrays match?

In [49]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)     # conditional selection method | Extract indices or replace elements conditionally

(array([1, 3, 5, 7]),)

exercise 14: how to extract all numbers between a given range from a numpy array?

In [55]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)

a = np.array([2, 6, 1, 9, 10, 3, 27])
(a >= 5) & (a <= 10)
a[(a >= 5) & (a <= 10)]

array([False,  True, False,  True,  True, False, False])

array([ 6,  9, 10])

exercise 15: how to make a python function that handles scalars to work on numpy arrays?

exercise 16: how to swap two columns in a 2d numpy array?

exercise 17: how to swap two rows in a 2d numpy array?

exercise 18: how to reverse the rows of a 2d array?

exercise 19: how to reverse the columns of a 2d array?

exercise 20: how to create a 2d array containing random floats between 5 and 10?

exercise 21. how to print only 3 decimal places in python numpy array?

exercise 22. how to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

exercise 23. how to limit the number of items printed in output of numpy array?

exercise 24. how to print the full numpy array without truncating

exercise 25. how to import a dataset with numbers and texts keeping the text intact in python numpy?

exercise 26. how to extract a particular column from 1D array of tuples?

exercise 27. how to convert a 1d array of tuples to a 2d numpy array?

exercise 28. how to compute the mean, median, standard deviation of a numpy array?